#!/usr/bin/env node
/**
 * import.mjs — turn one Talk To Figma `get_variables` dump into src/data/tokens.json.
 *
 *   node scripts/tokens/import.mjs <dump.json> [--collections all | "Primitives,Color Semantics"]
 *        [--source "Primitives library"] [--date 2026-09-17]
 *
 * The dump is the plugin's answer, run inside the file that DEFINES the variables
 * (the Primitives library). Every value in the output is read from it: aliases keep
 * the name they point at plus the value that name resolves to in the same mode.
 * Nothing is derived. Re-run when the library changes; never hand-edit tokens.json.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../../src/data/tokens.json');

const args = process.argv.slice(2);
const dumpPath = args.find((a) => !a.startsWith('--') && !isFlagValue(a));
function isFlagValue(a) {
  const i = args.indexOf(a);
  return i > 0 && args[i - 1].startsWith('--');
}
const flag = (name) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
};
if (!dumpPath) {
  console.error('usage: node scripts/tokens/import.mjs <dump.json> [--collections "A,B"] [--source name] [--date YYYY-MM-DD]');
  process.exit(1);
}

const dump = JSON.parse(fs.readFileSync(dumpPath, 'utf8'));
if (!Array.isArray(dump.collections)) {
  console.error(`${dumpPath}: not a get_variables dump (no "collections" array)`);
  process.exit(1);
}

const picked = flag('collections') ?? 'all';
const wanted = picked === 'all'
  ? dump.collections.map((c) => c.name)
  : picked.split(',').map((s) => s.trim()).filter(Boolean);
const missing = wanted.filter((w) => !dump.collections.some((c) => c.name === w));
if (missing.length) {
  console.error(`not in the dump: ${missing.join(', ')}`);
  console.error(`the dump has: ${dump.collections.map((c) => c.name).join(' · ')}`);
  process.exit(1);
}

// Every variable in the dump, by id — aliases may point into collections we don't export.
const byId = new Map();
for (const c of dump.collections) for (const v of c.variables ?? []) byId.set(v.id, { v, c });

const hex = ({ r, g, b }) =>
  '#' + [r, g, b].map((x) => Math.round(x * 255).toString(16).padStart(2, '0')).join('').toUpperCase();
const round = (n) => Math.round(n * 10000) / 10000;

/** A raw mode value as stored: numbers and strings as-is, colours as { hex, alpha }. */
function literal(x) {
  if (x && typeof x === 'object' && 'r' in x) return { hex: hex(x), alpha: round(x.a ?? 1) };
  return x;
}

/**
 * Follow an alias to a literal. A target in another collection is read in that
 * collection's mode of the same name if it has one, otherwise its first mode —
 * and the mode used is recorded, so the resolution is visible, not assumed.
 */
function resolve(x, modeName, seen = new Set()) {
  if (!(x && x.type === 'VARIABLE_ALIAS')) return { value: literal(x) };
  const hit = byId.get(x.id);
  if (!hit) return { alias: null, aliasId: x.id, value: null, note: 'alias target not in dump' };
  if (seen.has(x.id)) return { alias: hit.v.name, value: null, note: 'alias cycle' };
  seen.add(x.id);
  const mode = hit.c.modes.find((m) => m.name === modeName) ?? hit.c.modes[0];
  const inner = resolve(hit.v.valuesByMode[mode.modeId], mode.name, seen);
  const out = { alias: hit.v.name, aliasCollection: hit.c.name, value: inner.value };
  if (mode.name !== modeName) out.aliasMode = mode.name;
  if (inner.note) out.note = inner.note;
  return out;
}

const collections = [];
const tokens = [];
for (const c of dump.collections.filter((c) => wanted.includes(c.name))) {
  collections.push({ id: c.id, name: c.name, modes: c.modes.map((m) => m.name), count: (c.variables ?? []).length });
  for (const v of c.variables ?? []) {
    const values = {};
    for (const m of c.modes) values[m.name] = resolve(v.valuesByMode[m.modeId], m.name);
    tokens.push({
      name: v.name,
      group: v.name.split('/')[0],
      collection: c.name,
      type: v.resolvedType,
      id: v.id.replace(/^VariableID:/, ''),
      key: v.key,
      values,
    });
  }
}

const out = {
  $comment: 'Generated by scripts/tokens/import.mjs from a Talk To Figma get_variables dump. Do not edit by hand.',
  source: {
    file: flag('source') ?? 'Primitives library',
    dumpDate: flag('date') ?? new Date().toISOString().slice(0, 10),
    collections: wanted,
  },
  collections,
  tokens,
};

fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');
const groups = {};
for (const t of tokens) groups[`${t.collection} › ${t.group}`] = (groups[`${t.collection} › ${t.group}`] ?? 0) + 1;
console.log(`wrote ${path.relative(process.cwd(), OUT)} · ${tokens.length} tokens`);
for (const [g, n] of Object.entries(groups)) console.log(`  ${g.padEnd(32)} ${n}`);
const unresolved = tokens.filter((t) => Object.values(t.values).some((x) => x.value === null));
if (unresolved.length) {
  console.log(`\n${unresolved.length} with an unresolved value:`);
  for (const t of unresolved) console.log(`  ${t.name}`);
}
