#!/usr/bin/env node
/*
 * Framework sweep — measures every component data file against the rules the
 * workflow guides ask a human to check, with one real parser.
 *
 *   node scripts/audit/framework-sweep.mjs            aggregate + per-rule failures
 *   node scripts/audit/framework-sweep.mjs --matrix   also the per-component pass/fail matrix
 *   node scripts/audit/framework-sweep.mjs --json     full JSON (aggregate, matrix, per-component facts)
 *   node scripts/audit/framework-sweep.mjs --gate     exit 1 if any component fails a structural rule
 *                                                     (the merge gate — see .github/workflows/check.yml)
 *
 * Data: src/content/components/<slug>.json (the CMS files), loaded through the
 * same `fromJson` the site uses, so the sweep sees exactly what renders.
 *
 * Rules are scored against the guides as written (workflows/build/*.md and workflows/review/*.md). Where the
 * owner picks the CLAUDE.md variant instead (see FRAMEWORK-AUDIT.md §5), edit
 * the rule here — one place.
 */
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { fromJson, isSample, isTest } from '../../src/data/components/from-json.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const DATA_DIR = path.join(ROOT, 'src', 'content', 'components');
const DEMO_DIR = path.join(ROOT, 'public', 'scripts', 'demos');
// Playground layer data — generated by scripts/playground/build.mjs, never hand-edited.
const PG_DIR = path.join(ROOT, 'public', 'playground');

const args = new Set(process.argv.slice(2));
const allFiles = fs.readdirSync(DATA_DIR).filter((f) => f.endsWith('.json')).sort();
// Reference pages (slug `sample-*`) carry sample data: measured against every
// rule and reported apart, never counted with the components.
// Test pages (slug `test-*`) are a trial read of a component outside the
// inventory: scored for information only, never counted and never gated.
const slugOf = (f) => f.replace(/\.json$/, '');
const files = allFiles.filter((f) => !isSample(slugOf(f)) && !isTest(slugOf(f)));
const refFiles = allFiles.filter((f) => isSample(slugOf(f)));
const testFiles = allFiles.filter((f) => isTest(slugOf(f)));

// ── Loader ─────────────────────────────────────────────────────────────
function load(file) {
  return fromJson(file.replace(/\.json$/, ''), JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf8')));
}

// ── Facts per component ─────────────────────────────────────────────────
const DS = ['keep', 'fix', 'restructure', 'consolidate', 'product-layer', 'remove'];
const NATIVE = ['ready', 'refine', 'rework', 'na', 'fix', 'empty'];
const CANON_RECO = new Set(['Rename', 'Property', 'Slot', 'State', 'Token', 'Asset', 'Composition', 'Family', 'A11y', 'Docs']);
const LAYOUT_KEYS = new Set(['Height', 'Width', 'Radius', 'Padding H', 'Padding V', 'Gap', 'Border', 'Alignment']);
// "Font", "Size", … and compound keys like "Title font" / "Title size" — a
// font spec is never a text-style name.
const TYPO_BAD = /(^|\s)(font|size|tracking|line-height|line height|weight|letter-spacing|letter spacing)$/i;
// A verdict-box title opens with the verdict it is announcing, as in
// "Fix — three findings to close" (OVERVIEW-REVIEW-GUIDE.md §0).
const VERDICT_LEAD = /^(Keep|Fix|Restructure|Consolidate|Product Layer|Remove)\b/i;
// Two lines of verdict text at the page's measure.
const VERDICT_MAX = 240;
const GUIDE_ORDER = 'Properties → Colors → Typography → Layout';
const SECTION_ORDER = ['Properties', 'Colors', 'Typography', 'Layout'];
const strip = (s) => (s || '').replace(/<[^>]+>/g, '').trim();

function facts(slug, d) {
  const m = d.meta || {}, o = d.overview || {}, s = d.style || {}, c = d.code || {}, ch = d.changelog || [];
  const badges = (m.badges || []).map((b) => b.kind);
  const dsVerdict = badges.find((k) => DS.includes(k)) || null;
  const nativeStatus = badges.find((k) => NATIVE.includes(k) && k !== dsVerdict) || null;
  const cards = s.specCards || [];
  const rows = (label) => cards.flatMap((x) => (x.sections || []).filter((sec) => sec.label === label).flatMap((sec) => sec.rows));
  const typo = rows('Typography');
  const tables = s.colorsTables || [];
  const inst = c.installation || {};
  const instText = (inst.blocks || []).map((b) => strip(b.label + ' ' + b.code)).join('\n');
  const pm = (c.propertyMapping || {}).rows || [];
  const v = c.variants || {};
  const demoPath = path.join(DEMO_DIR, slug + '.js');
  const demo = fs.existsSync(demoPath) ? fs.readFileSync(demoPath, 'utf8') : null;
  const semver = (x) => String(x || '').split('.').map(Number);
  let newestFirst = true;
  for (let i = 1; i < ch.length; i++) {
    const a = semver(ch[i - 1].version), b = semver(ch[i].version);
    if (a.some(isNaN) || b.some(isNaN)) continue;
    if (a[0] < b[0] || (a[0] === b[0] && a[1] < b[1]) || (a[0] === b[0] && a[1] === b[1] && a[2] < b[2])) newestFirst = false;
  }
  return {
    slug, name: m.name || slug, navGroup: m.navGroup || null, dsVerdict, nativeStatus,
    metaNode: m.node || '',
    styleSource: s.source || null,
    // ── Playground opt-in ────────────────────────────────────────────
    // A component opted in has no hand-authored spec cards: its Style tab IS
    // the Playground, so S1–S12 stop applying and P1–P5 take over. Everything
    // without the flag is unchanged.
    playground: s.playground === true,
    ...(() => {
      if (s.playground !== true) return { pgData: null, pgHashOk: false, pgSet: null, pgVariants: 0, pgProps: 0, pgProvenance: false, pgTokens: false };
      const f = path.join(PG_DIR, `${slug}.json`);
      if (!fs.existsSync(f)) return { pgData: false, pgHashOk: false, pgSet: null, pgVariants: 0, pgProps: 0, pgProvenance: false, pgTokens: false };
      try {
        const d = JSON.parse(fs.readFileSync(f, 'utf8'));
        const hash = createHash('sha256')
          .update(JSON.stringify({ properties: d.properties, variants: d.variants, svgs: d.svgs, images: d.images }))
          .digest('hex').slice(0, 16);
        return {
          pgData: true,
          pgHashOk: !!d.meta?.hash && d.meta.hash === hash,
          pgSet: d.meta?.setId || null,
          pgVariants: (d.variants || []).length,
          pgProps: (d.properties || []).length,
          pgProvenance: !!d.meta?.figma?.version,
          pgTokens: !!d.meta?.tokens,
        };
      } catch { return { pgData: false, pgHashOk: false, pgSet: null, pgVariants: 0, pgProps: 0, pgProvenance: false, pgTokens: false }; }
    })(),
    unread: rows('Layout').filter((r) => /^[—–-]$/.test((r.value || '').trim())).length
      + tables.reduce((n, t) => n + t.rows.filter((r) => /^[—–-]$/.test((r.token || '').trim())).length, 0),
    badgeCount: badges.length, verdictBox: !!m.verdict,
    // The verdict box: a title that opens with the verdict word, then text
    // of at most two lines. Two lines is ~240 characters at the page's
    // measure — the reference page sits at 163, the guide's example at 107.
    verdictTitleLeads: VERDICT_LEAD.test(strip(m.verdict?.title)),
    verdictTextLen: strip(m.verdict?.text).length,
    cardlessVerdict: ['remove', 'consolidate', 'product-layer'].includes(dsVerdict),
    traits: (o.traits || []).map((t) => t.name), traitRatings: (o.traits || []).map((t) => t.rating),
    behaviorRows: (o.behavior || []).length,
    open: (o.open || []).length, resolved: (o.resolved || []).length,
    recos: (o.recommendations || []).length, applied: (o.appliedRecommendations || []).length,
    openC7: (o.open || []).filter((i) => i.tag?.criterion === 'C7').length,
    openMalformed: (o.open || []).filter((i) => !i.headline || !i.tag).length,
    recoBadTags: (o.recommendations || []).map((i) => i.tag).filter((t) => !CANON_RECO.has(t)),
    inContext: !!(o.inContextHtml || o.inContextImage || o.inContextNote),
    inContextVisual: !!(o.inContextHtml || o.inContextImage), livePreview: !!o.livePreviewHtml,
    cards: cards.length,
    cardTitleBad: cards.filter((x) => /[·=—–:]/.test(x.title || '')).length,
    cardDemoAbsent: cards.filter((x) => x.demoControls === undefined).length,
    cardNoPreview: cards.filter((x) => !(x.previewHtml || '').trim()).length,
    sectionOrders: cards.map((x) => (x.sections || []).map((sec) => sec.label).join(' → ')),
    // Sections run Properties → Colors → Typography → Layout; an Examples card
    // carries only the sections its property changes, so a subset in that
    // order passes, and Properties is always first.
    sectionOrderBad: cards.filter((x) => {
      const labels = (x.sections || []).map((sec) => sec.label);
      const idx = labels.map((l) => SECTION_ORDER.indexOf(l));
      return labels[0] !== 'Properties' || idx.some((i, n) => i < 0 || (n > 0 && i <= idx[n - 1]));
    }).length,
    layoutExtraKeys: [...new Set(rows('Layout').map((r) => r.key).filter((k) => !LAYOUT_KEYS.has(k)))],
    typoRows: typo.length,
    typoFontRows: typo.filter((r) => TYPO_BAD.test(r.key)).length,
    typoDashRows: typo.filter((r) => /^[—–-]$/.test((r.value || '').trim())).length,
    typoStyleNames: typo.filter((r) => /^(Primary|Secondary|Component|Hiraya)\//.test(r.value || '')).length,
    colorsRowsPerState: rows('Colors').filter((r) => /\b(pressed|disabled|hover|focused)\b/i.test(r.key)).length,
    rowsWithVariants: cards.flatMap((x) => (x.sections || []).flatMap((sec) => sec.rows)).filter((r) => r.variants).length,
    devEmpty: cards.filter((x) => strip(x.swift).length < 20 || strip(x.compose).length < 20).length,
    devContainerCode: cards.filter((x) => /HStack|VStack|Constants\.|\.cornerRadius\(/.test((x.swift || '') + (x.compose || ''))).length,
    colorsTables: tables.length,
    colorsTableColumns: tables.map((t) => t.columns.join(' | ')),
    colorsTableTitles: tables.map((t) => t.title),
    colorsTablesElementShape: tables.filter((t) => t.columns.length === 1 && t.columns[0] === 'Value' && t.rows.every((r) => r.element)).length,
    resolvedC7: (o.resolved || []).filter((i) => i.tag?.criterion === 'C7').length,
    scorecardC7: (c.scorecard || []).filter((x) => x.id === 'C7').length,
    backfilled: ch.some((e) => /^Documentation backfill/.test(e.header || '')),
    demoScript: !!demo, demoGetSnippet: !!demo && /getSnippet/.test(demo),
    installBlocks: (inst.blocks || []).length, installPlanned: inst.planned === true,
    // `planned: true` already renders the "Planned API" badge beside the
    // heading, so a footnote under the blocks only repeats it.
    installFootnote: !!strip(inst.footnote),
    installOldCoords: /com\.gcash\.eastblue/.test(instText),
    installImport: /\bimport\s/.test(instText),
    installVersion: (instText.match(/:(\d+\.\d+\.\d+)/) || [])[1] || null,
    pmRows: pm.length,
    pmRowsEq: pm.filter((r) => /=/.test(strip(r.figma))).length,
    pmRowsCode: pm.filter((r) => /<code>/.test(r.figma)).length,
    usageSnippets: (c.usageSnippets || []).length,
    // Usage Snippets render through `set:html` and nothing highlights them
    // on the client, so the syn-* spans have to be in the data file. The
    // tokenizer in public/scripts/assessment.js is the one source for them.
    usagePlain: (c.usageSnippets || []).filter((u) => !/class="syn-/.test((u.swift || '') + (u.compose || ''))).length,
    synStale: /class="syn-eq"/.test(JSON.stringify(c)),
    usageContainerCode: (c.usageSnippets || []).filter((u) => /HStack|VStack|Constants\./.test(u.swift + u.compose)).length,
    a11yRows: (c.accessibility || []).length,
    a11yOnePlatform: (c.accessibility || []).filter((a) => !strip(a.ios) || !strip(a.android) || /^[—–-]$/.test(strip(a.ios)) || /^[—–-]$/.test(strip(a.android))).length,
    guidelines: (c.usageGuidelines || []).length,
    scorecardIds: (c.scorecard || []).map((x) => x.id),
    scorecardStatuses: (c.scorecard || []).map((x) => x.status),
    scorecardReadyButOpen: (c.scorecard || []).filter((x) => x.status === 'ready' && (o.open || []).some((i) => i.tag?.criterion === x.id)).map((x) => x.id),
    variantsTotal: v.total || 0, variantsDesc: v.description || '',
    variantsSummary: !!v.summary, variantsCollapse: v.collapseLabel || null,
    changelog: ch.length,
    changelogBadDates: ch.filter((e) => !/^(January|February|March|April|May|June|July|August|September|October|November|December) \d{4}$/.test(e.date)).map((e) => e.date),
    changelogHeaderNoNode: ch.filter((e) => !/nodes?\s+\d+:\d+/i.test(e.header)).length,
    changelogNewestFirst: newestFirst,
    changelogResolvedRows: ch.reduce((n, e) => n + (e.rows || []).filter((r) => r.delta?.kind === 'resolved').length, 0),
  };
}

// ── Rules — one per line of the guides' fixed content lists ─────────────
// A remove / consolidate / product-layer component has no Style or Code
// tab, so those rules pass as not applicable (`na`).
const na = (fn) => (c) => c.cardlessVerdict || fn(c);
// A Style rule describes the hand-authored spec-card tab. A component opted in
// to the Playground has no spec cards to measure — the P rules measure it
// instead — so its S rules pass as not applicable, exactly as a cardless
// verdict's do. Code rules still apply: the Code tab is unchanged.
const styleRule = (fn) => (c) => c.cardlessVerdict || c.playground || fn(c);
export const RULES = [
  ['M1', 'Header',    'DS verdict + native status badge pair',                      (c) => c.badgeCount === 2 && !!c.dsVerdict && !!c.nativeStatus],
  ['M2', 'Header',    'Verdict box present',                                         (c) => c.verdictBox],
  ['M3', 'Header',    'Verdict box: title leads with the verdict, text ≤ two lines', (c) => c.verdictTitleLeads && c.verdictTextLen > 0 && c.verdictTextLen <= VERDICT_MAX],
  ['O1', 'Overview',  'Four canonical traits',                                       (c) => c.traits.length === 4],
  ['O2', 'Overview',  'keep ⇒ all four traits pass',                                 (c) => !(c.dsVerdict === 'keep' && c.traitRatings.some((x) => x !== 'pass'))],
  ['O3', 'Overview',  'Behavior table present (interactive components)',             (c) => c.cardlessVerdict || c.behaviorRows > 0],
  ['O4', 'Overview',  'No C7 anywhere: open, resolved, scorecard',                   (c) => c.openC7 === 0 && c.resolvedC7 === 0 && c.scorecardC7 === 0],
  ['O5', 'Overview',  'Open items carry headline + tag',                             (c) => c.openMalformed === 0],
  ['O6', 'Overview',  'Recommendation tags from the canonical ten',                  (c) => c.recoBadTags.length === 0],
  ['O7', 'Overview',  'In Context has a visual (the component on a real screen)',    (c) => c.cardlessVerdict || c.inContextVisual],
  ['S1', 'Style',     'Cards present, or cardless by verdict',                       styleRule((c) => c.cards > 0)],
  ['S2', 'Style',     'Card titles are bare property names',                         styleRule((c) => c.cardTitleBad === 0)],
  ['S3', 'Style',     'Every card has a server-rendered preview',                    styleRule((c) => c.cardNoPreview === 0)],
  ['S4', 'Style',     'demoControls declared on every card',                         styleRule((c) => c.cardDemoAbsent === 0)],
  ['S5', 'Style',     'Sections in guide order P → C → T → L, Properties first',     styleRule((c) => c.sectionOrderBad === 0)],
  ['S6', 'Style',     'Layout uses only the eight keys',                             styleRule((c) => c.layoutExtraKeys.length === 0)],
  ['S7', 'Style',     'Typography is style names only',                              styleRule((c) => c.typoFontRows === 0 && c.typoDashRows === 0 && (c.typoRows === 0 || c.typoStyleNames > 0))],
  ['S8', 'Style',     'Colors table is Role │ Element │ Token │ Value',              styleRule((c) => c.colorsTables > 0 && c.colorsTablesElementShape === c.colorsTables)],
  ['S9', 'Style',     'DEV code live (getSnippet defined)',                          styleRule((c) => c.demoGetSnippet)],
  ['S10', 'Style',    'DEV code non-empty and component API',                        styleRule((c) => c.devEmpty === 0 && c.devContainerCode === 0)],
  ['S11', 'Style',    'Style tab read from the current set (style.source.set = meta.node)', styleRule((c) => !!c.styleSource && c.styleSource.set === c.metaNode)],
  ['S12', 'Style',    'No unread values (— in Layout rows or colors-table tokens)',  styleRule((c) => c.unread === 0)],
  // ── Playground — the Style tab on an opted-in component ──────────────
  // Measured only when style.playground is true; not applicable otherwise.
  // These are PLAYGROUND-REVIEW-GUIDE.md §B5 checks 1–4 and 10, the ones a
  // static read of the repo can answer. Checks 5–9 (smoke, reflow, a11y,
  // fidelity, cross-browser) need a browser and belong to npm run playground:checks.
  ['P1', 'Playground', 'Layer data exists for an opted-in component',                 (c) => !c.playground || c.pgData === true],
  ['P2', 'Playground', 'Layer data is generated, not hand-edited (meta.hash)',        (c) => !c.playground || c.pgHashOk],
  ['P3', 'Playground', 'Provenance recorded (Figma version at build)',                (c) => !c.playground || c.pgProvenance],
  ['P4', 'Playground', 'Read from the component set on the page (setId = meta.node)', (c) => !c.playground || c.pgSet === c.metaNode],
  ['P5', 'Playground', 'Variants and properties present, tokens source named',        (c) => !c.playground || (c.pgVariants > 0 && c.pgProps > 0 && c.pgTokens)],
  ['K1', 'Code',      'Installation canonical: SPM + Gradle + Import, 1.0.0, planned', na((c) => c.installBlocks === 3 && c.installImport && !c.installOldCoords && c.installVersion === '1.0.0' && c.installPlanned)],
  ['K2', 'Code',      'Property Mapping grouped prose',                              na((c) => c.pmRows > 0 && c.pmRowsEq === 0 && c.pmRowsCode === 0)],
  ['K3', 'Code',      'Usage Snippets present, component API',                       na((c) => c.usageSnippets > 0 && c.usageContainerCode === 0)],
  ['K4', 'Code',      'Accessibility answers both platforms',                        na((c) => c.a11yRows > 0 && c.a11yOnePlatform === 0)],
  ['K5', 'Code',      'Usage Guidelines present, ≤ 4 pairs',                         na((c) => c.guidelines > 0 && c.guidelines <= 4)],
  ['K6', 'Code',      'Scorecard is exactly C1–C6',                                  na((c) => c.scorecardIds.join() === 'C1,C2,C3,C4,C5,C6')],
  ['K7', 'Code',      'Scorecard statuses in vocabulary (no empty)',                 na((c) => c.scorecardIds.length > 0 && !c.scorecardStatuses.includes('empty'))],
  ['K8', 'Code',      'Variants total + multiplier + summary/collapse when > 10',    na((c) => c.variantsTotal > 0 && /×|x/.test(c.variantsDesc) && (c.variantsTotal <= 10 || (c.variantsSummary && !!c.variantsCollapse)))],
  ['K9', 'Code',      'No Installation footnote (the Planned API badge says it)',    na((c) => !c.installFootnote)],
  ['K10', 'Code',     'Usage Snippets carry syntax-highlight spans, none stale',     na((c) => c.usageSnippets > 0 && c.usagePlain === 0 && !c.synStale)],
  ['L1', 'Changelog', 'Entries dated Month YYYY, node in header, newest first',      (c) => c.changelog > 0 && c.changelogBadDates.length === 0 && c.changelogHeaderNoNode === 0 && c.changelogNewestFirst],
  ['L2', 'Changelog', 'Every resolved issue has a row, or one backfill entry',       (c) => c.resolved <= c.changelogResolvedRows || c.backfilled],
];

// ── Run ─────────────────────────────────────────────────────────────────
const components = [];
const errors = [];
for (const f of files) {
  const slug = f.replace(/\.json$/, '');
  try {
    const d = load(f);
    if (!d) throw new Error('no ComponentData export');
    components.push(facts(slug, d));
  } catch (e) { errors.push({ slug, error: e.message }); }
}

const score = (c) => {
  const fails = RULES.filter(([, , , fn]) => !fn(c)).map(([code]) => code);
  return { slug: c.slug, name: c.name, dsVerdict: c.dsVerdict, nativeStatus: c.nativeStatus, cards: c.cards, pass: RULES.length - fails.length, fails };
};
const matrix = components.map(score);

// Reference pages — the framework shown whole on sample data. Every rule
// must hold on them, so a page that drifts from the framework fails the gate.
const reference = [];
for (const f of refFiles) {
  const slug = f.replace(/\.json$/, '');
  try { reference.push(score(facts(slug, load(f)))); } catch (e) { errors.push({ slug, error: e.message }); }
}
// Test pages — scored the same way, reported apart, never gated.
const testPages = [];
for (const f of testFiles) {
  const slug = slugOf(f);
  try { testPages.push(score(facts(slug, load(f)))); } catch (e) { errors.push({ slug, error: e.message }); }
}
const failCounts = RULES.map(([code, tab, label]) => ({ code, tab, label, failing: matrix.filter((m) => m.fails.includes(code)).length }))
  .sort((a, b) => b.failing - a.failing);
const dist = {};
for (const m of matrix) dist[m.pass] = (dist[m.pass] || 0) + 1;
const sortedPass = matrix.map((m) => m.pass).sort((a, b) => a - b);
const median = sortedPass[Math.floor(sortedPass.length / 2)];

// Structural rules hold on every component today and must keep holding;
// content rules need a Figma read and are reported, not gated.
const HARD = new Set(['M1', 'M2', 'O1', 'O2', 'O4', 'O5', 'O6', 'S1', 'S4', 'S10', 'K1', 'K6', 'K7', 'L2']);
if (args.has('--gate')) {
  const broken = matrix.filter((m) => m.fails.some((f) => HARD.has(f)));
  const drifted = reference.filter((m) => m.fails.length);
  if (errors.length) { for (const e of errors) console.log(`parse error: ${e.slug}: ${e.error}`); }
  if (broken.length || drifted.length || errors.length) {
    if (broken.length) console.log(`Gate: ${broken.length} component(s) fail a structural rule`);
    for (const m of broken) console.log(`  ${m.slug}: ${m.fails.filter((f) => HARD.has(f)).join(' ')}`);
    if (drifted.length) console.log(`Gate: ${drifted.length} reference page(s) fail a rule (every rule must hold on a reference page)`);
    for (const m of drifted) console.log(`  ${m.slug}: ${m.fails.join(' ')}`);
    process.exit(1);
  }
  console.log(`Gate: all ${components.length} components pass the ${HARD.size} structural rules` + (reference.length ? ` · ${reference.length} reference page(s) pass all ${RULES.length}` : ''));
  process.exit(0);
}

if (args.has('--json')) {
  console.log(JSON.stringify({ date: new Date().toISOString().slice(0, 10), componentCount: components.length, rules: RULES.map(([code, tab, label]) => ({ code, tab, label })), failCounts, distribution: dist, median, matrix, components, reference, testPages, errors }, null, 2));
  process.exit(0);
}

console.log(`\nFramework sweep — ${components.length} components · ${RULES.length} rules · ${errors.length} parse errors`);
console.log('────────────────────────────────────────────────────────────────');
console.log('  Rule failures (components failing each rule)');
for (const r of failCounts) console.log(`  ${String(r.failing).padStart(3)}  ${r.code.padEnd(4)} ${r.tab.padEnd(10)} ${r.label}`);
console.log('\n  Rules passed per component');
for (const k of Object.keys(dist).map(Number).sort((a, b) => b - a)) console.log(`  ${String(k).padStart(3)} / ${RULES.length}   ${'█'.repeat(dist[k])} ${dist[k]}`);
console.log(`\n  Median: ${median} / ${RULES.length} · fully compliant: ${matrix.filter((m) => m.fails.length === 0).length}`);
if (reference.length) {
  console.log('\n  Reference pages (sample data — measured apart, never counted)');
  for (const m of reference) console.log(`  ${String(m.pass).padStart(3)} / ${RULES.length}   ${m.slug}${m.fails.length ? '   fails ' + m.fails.join(' ') : ''}`);
}
if (testPages.length) {
  console.log('\n  Test pages (trial reads — measured apart, never counted, never gated)');
  for (const m of testPages) console.log(`  ${String(m.pass).padStart(3)} / ${RULES.length}   ${m.slug}${m.fails.length ? '   fails ' + m.fails.join(' ') : ''}`);
}
if (errors.length) { console.log('\n  Parse errors'); for (const e of errors) console.log(`  ${e.slug}: ${e.error}`); }

if (args.has('--matrix')) {
  console.log('\n  Per-component matrix (worst first)');
  for (const m of [...matrix].sort((a, b) => a.pass - b.pass || a.slug.localeCompare(b.slug))) {
    console.log(`  ${String(m.pass).padStart(3)}  ${m.slug.padEnd(30)} ${m.fails.join(' ')}`);
  }
}
console.log('');
